package settings

var Default = map[string]interface{}{

	"min_compress_block_size":                        uint64(DEFAULT_BLOCK_SIZE),
	"max_compress_block_size":                        uint64(DEFAULT_BLOCK_SIZE * 16),
	"max_block_size":                                 uint64(DEFAULT_BLOCK_SIZE),
	"max_insert_block_size":                          uint64(DEFAULT_INSERT_BLOCK_SIZE),
	"min_insert_block_size_rows":                     uint64(DEFAULT_INSERT_BLOCK_SIZE),
	"min_insert_block_size_bytes":                    uint64(DEFAULT_INSERT_BLOCK_SIZE * 256),
	"max_read_buffer_size":                           uint64(DBMS_DEFAULT_BUFFER_SIZE),
	"max_distributed_connections":                    uint64(1024),
	"max_query_size":                                 uint64(262144),
	"interactive_delay":                              uint64(100000),
	"poll_interval":                                  uint64(DBMS_DEFAULT_POLL_INTERVAL),
	"distributed_connections_pool_size":              uint64(DBMS_DEFAULT_DISTRIBUTED_CONNECTIONS_POOL_SIZE),
	"connections_with_failover_max_tries":            uint64(DBMS_CONNECTION_POOL_WITH_FAILOVER_DEFAULT_MAX_TRIES),
	"background_pool_size":                           uint64(16),
	"background_schedule_pool_size":                  uint64(16),
	"replication_alter_partitions_sync":              uint64(1),
	"replication_alter_columns_timeout":              uint64(16),
	"min_count_to_compile":                           uint64(3),
	"min_count_to_compile_expression":                uint64(3),
	"group_by_two_level_threshold":                   uint64(100000),
	"group_by_two_level_threshold_bytes":             uint64(100000000),
	"aggregation_memory_efficient_merge_threads":     uint64(0),
	"max_parallel_replicas":                          uint64(1),
	"parallel_replicas_count":                        uint64(0),
	"parallel_replica_offset":                        uint64(0),
	"merge_tree_min_rows_for_concurrent_read":        uint64(MERGE_TREE_MIN_ROWS_FOR_CONCURRENT_READ),
	"merge_tree_min_bytes_for_concurrent_read":       uint64(0),
	"merge_tree_min_rows_for_seek":                   uint64(0),
	"merge_tree_min_bytes_for_seek":                  uint64(0),
	"merge_tree_coarse_index_granularity":            uint64(0),
	"merge_tree_max_rows_to_use_cache":               uint64(MERGE_TREE_MAX_ROWS_TO_USE_CACHE),
	"merge_tree_max_bytes_to_use_cache":              uint64(0),
	"mysql_max_rows_to_insert":                       uint64(DEFAULT_BLOCK_SIZE),
	"optimize_min_equality_disjunction_chain_length": uint64(3),
	"min_bytes_to_use_direct_io":                     uint64(0),
	"mark_cache_min_lifetime":                        uint64(10000),
	"priority":                                       uint64(0),
	"log_queries_cut_to_length":                      uint64(100000),
	"max_concurrent_queries_for_user":                uint64(0),
	"insert_quorum":                                  uint64(0),
	"select_sequential_consistency":                  uint64(0),
	"table_function_remote_max_addresses":            uint64(1000),
	"read_backoff_max_throughput":                    uint64(1048576),
	"read_backoff_min_events":                        uint64(2),
	"output_format_pretty_max_rows":                  uint64(10000),
	"output_format_pretty_max_column_pad_width":      uint64(250),
	"output_format_parquet_row_group_size":           uint64(1000000),
	"http_headers_progress_interval_ms":              uint64(100),
	"input_format_allow_errors_num":                  uint64(0),
	"preferred_block_size_bytes":                     uint64(1000000),
	"max_replica_delay_for_distributed_queries":      uint64(120),
	"preferred_max_column_in_block_size_bytes":       uint64(0),
	"insert_distributed_timeout":                     uint64(0),
	"odbc_max_field_size":                            uint64(1024),
	"max_rows_to_read":                               uint64(0),
	"max_bytes_to_read":                              uint64(0),
	"max_rows_to_group_by":                           uint64(0),
	"max_bytes_before_external_group_by":             uint64(0),
	"max_rows_to_sort":                               uint64(0),
	"max_bytes_to_sort":                              uint64(0),
	"max_bytes_before_external_sort":                 uint64(0),
	"max_bytes_before_remerge_sort":                  uint64(1000000000),
	"max_result_rows":                                uint64(0),
	"max_result_bytes":                               uint64(0),
	"min_execution_speed":                            uint64(0),
	"max_execution_speed":                            uint64(0),
	"min_execution_speed_bytes":                      uint64(0),
	"max_execution_speed_bytes":                      uint64(0),
	"max_columns_to_read":                            uint64(0),
	"max_temporary_columns":                          uint64(0),
	"max_temporary_non_const_columns":                uint64(0),
	"max_subquery_depth":                             uint64(100),
	"max_pipeline_depth":                             uint64(1000),
	"max_ast_depth":                                  uint64(1000),
	"max_ast_elements":                               uint64(50000),
	"max_expanded_ast_elements":                      uint64(50000),
	"readonly":                                       uint64(0),
	"max_rows_in_set":                                uint64(0),
	"max_bytes_in_set":                               uint64(0),
	"max_rows_in_join":                               uint64(0),
	"max_bytes_in_join":                              uint64(0),
	"max_rows_to_transfer":                           uint64(0),
	"max_bytes_to_transfer":                          uint64(0),
	"max_rows_in_distinct":                           uint64(0),
	"max_bytes_in_distinct":                          uint64(0),
	"max_memory_usage":                               uint64(0),
	"max_memory_usage_for_user":                      uint64(0),
	"max_memory_usage_for_all_queries":               uint64(0),
	"max_network_bandwidth":                          uint64(0),
	"max_network_bytes":                              uint64(0),
	"max_network_bandwidth_for_user":                 uint64(0),
	"max_network_bandwidth_for_all_users":            uint64(0),
	"low_cardinality_max_dictionary_size":            uint64(8192),
	"max_fetch_partition_retries_count":              uint64(5),
	"http_max_multipart_form_data_size":              uint64(HTTP_MAX_MULTIPART_FORM_DATA_SIZE),
	"max_partitions_per_insert_block":                uint64(100),
	"max_threads":                                    uint64(0),

	"network_zstd_compression_level": int64(1),
	"http_zlib_compression_level":    int64(3),
	"distributed_ddl_task_timeout":   int64(180),

	"extremes":               false,
	"use_uncompressed_cache": true,
	"replace_running_query":  false,
	"distributed_directory_monitor_batch_inserts":                false,
	"optimize_move_to_prewhere":                                  true,
	"compile":                                                    false,
	"allow_suspicious_low_cardinality_types":                     false,
	"compile_expressions":                                        false,
	"distributed_aggregation_memory_efficient":                   false,
	"skip_unavailable_shards":                                    false,
	"distributed_group_by_no_merge":                              false,
	"optimize_skip_unused_shards":                                false,
	"merge_tree_uniform_read_distribution":                       true,
	"force_index_by_date":                                        false,
	"force_primary_key":                                          false,
	"log_queries":                                                false,
	"insert_deduplicate":                                         true,
	"enable_http_compression":                                    false,
	"http_native_compression_disable_checksumming_on_decompress": false,
	"output_format_write_statistics":                             true,
	"add_http_cors_header":                                       false,
	"input_format_skip_unknown_fields":                           false,
	"input_format_with_names_use_header":                         false,
	"input_format_import_nested_json":                            false,
	"input_format_defaults_for_omitted_fields":                   false,
	"input_format_values_interpret_expressions":                  true,
	"output_format_json_quote_64bit_integers":                    false,
	"output_format_json_quote_denormals":                         false,
	"output_format_json_escape_forward_slashes":                  true,
	"output_format_pretty_color":                                 true,
	"use_client_time_zone":                                       false,
	"send_progress_in_http_headers":                              false,
	"fsync_metadata":                                             true,
	"join_use_nulls":                                             false,
	"fallback_to_stale_replicas_for_distributed_queries":         true,
	"insert_distributed_sync":                                    false,
	"insert_allow_materialized_columns":                          false,
	"optimize_throw_if_noop":                                     false,
	"use_index_for_in_with_subqueries":                           true,
	"empty_result_for_aggregation_by_empty_set":                  false,
	"allow_distributed_ddl":                                      true,
	"join_any_take_last_row":                                     false,
	"format_csv_allow_single_quotes":                             true,
	"format_csv_allow_double_quotes":                             true,
	"log_profile_events":                                         true,
	"log_query_settings":                                         true,
	"log_query_threads":                                          true,
	"enable_optimize_predicate_expression":                       false,
	"low_cardinality_use_single_dictionary_for_part":             false,
	"decimal_check_overflow":                                     true,
	"prefer_localhost_replica":                                   true,
	"calculate_text_stack_trace":                                 true,
	"allow_ddl":                                                  true,
	"parallel_view_processing":                                   false,
	"enable_debug_queries":                                       true,
	"enable_unaligned_array_join":                                false,
	"low_cardinality_allow_in_native_format":                     true,
	"allow_experimental_multiple_joins_emulation":                true,
	"allow_experimental_cross_to_join_conversion":                true,
	"cancel_http_readonly_queries_on_client_close":               false,
	"external_table_functions_use_nulls":                         true,
	"allow_experimental_data_skipping_indices":                   false,
	"allow_hyperscan":                                            true,
	"allow_simdjson":                                             true,

	"connect_timeout":                             uint64(DBMS_DEFAULT_CONNECT_TIMEOUT_SEC),
	"connect_timeout_with_failover_ms":            uint64(DBMS_DEFAULT_CONNECT_TIMEOUT_WITH_FAILOVER_MS),
	"receive_timeout":                             uint64(DBMS_DEFAULT_RECEIVE_TIMEOUT_SEC),
	"send_timeout":                                uint64(DBMS_DEFAULT_SEND_TIMEOUT_SEC),
	"tcp_keep_alive_timeout":                      uint64(0),
	"queue_max_wait_ms":                           uint64(5000),
	"distributed_directory_monitor_sleep_time_ms": uint64(100),
	"insert_quorum_timeout":                       uint64(600000),
	"read_backoff_min_latency_ms":                 uint64(1000),
	"read_backoff_min_interval_between_events_ms": uint64(1000),
	"stream_flush_interval_ms":                    uint64(7500),
	"stream_poll_timeout_ms":                      uint64(500),
	"http_connection_timeout":                     uint64(DEFAULT_HTTP_READ_BUFFER_CONNECTION_TIMEOUT),
	"http_send_timeout":                           uint64(DEFAULT_HTTP_READ_BUFFER_TIMEOUT),
	"http_receive_timeout":                        uint64(DEFAULT_HTTP_READ_BUFFER_TIMEOUT),
	"max_execution_time":                          uint64(0),
	"timeout_before_checking_execution_speed":     uint64(0),

	//Newly added
	"send_logs_level":        "fatal",
	"read_overflow_mode":     read_overflow_mode,
	"totals_mode":            AFTER_HAVING_EXCLUSIVE,
	"group_by_overflow_mode": group_by_overflow_mode,

	"joined_subquery_requires_alias": false,

	"enable_operator_level_profile": false,
	"enable_query_level_profiling":  false,

	"totals_auto_threshold": float32(0),

	"idle_connection_timeout": uint64(3600),

	"additional_background_pool_size":       uint64(8),
	"background_consume_schedule_pool_size": uint64(16),
	"background_dump_thread_pool_size":      uint64(16),
	"local_disk_cache_thread_pool_size":     uint64(16),
	"max_insert_block_size_bytes":           uint64(DEFAULT_BLOCK_SIZE_BYTES),
	"load_balancing":                        LoadBalancing,
	"load_balancing_offset":                 uint64(0),

	"query_cache_min_lifetime": uint64(1000),

	"part_cache_min_lifetime":          uint64(3600),
	"max_streams_to_max_threads_ratio": float32(1),

	"network_compression_method": "LZ4",

	"distributed_product_mode": DistributedProductMode,

	"free_resource_early_in_write":      false,
	"optimize_map_column_serialization": false,

	"memory_tracker_fault_probability": float32(0),

	"count_distinct_implementation": "uniqExact",

	"input_format_json_aggregate_function_type_base64_encode": false,

	"input_format_allow_errors_ratio": float32(0),

	"join_default_strictness": "JoinStrictness",

	"max_replica_delay_for_write_queries": uint64(0),

	"kafka_session_timeout_ms":        uint64(180000),
	"kafka_max_partition_fetch_bytes": uint64(1048576),
	"format_schema":                   "",

	"funnel_old_rule":                  false,
	"distributed_perfect_shard":        false,
	"disable_perfect_shard_auto_merge": false,
	"snappy_format_blocked":            false,
	"skip_nullinput_notnull_col":       false,
	"deduce_part_eliminate":            true,
	"optimize_subpart_number":          int64(-1),
	"optimize_subpart_key":             int64(-1),
	"enable_bloom_filter":              false,
	"enable_range_bloom_filter":        false,
	"parallel_fetch_part":              uint64(1),
	"disable_remote_stream_log":        false,
	"decrease_error_period":            uint64(600),
	"enable_sync_from_ha":              false,
	"pathgraph_threshold_y":            uint64(0),
	"pathgraph_threshold_x":            uint64(0),

	"enable_dictionary_compression":        false,
	"enable_sync_fetch":                    false,
	"TEST_KNOB":                            uint64(0),
	"enable_sample_by_range":               false,
	"enable_deterministic_sample_by_range": false,
	"enable_final_sample":                  false,
	"max_sample_size_for_optimize":         uint64(1000000),
	"enable_ab_index_optimization":         false,
	"enable_sync_build_bitmap":             false,
	"enable_async_build_bitmap_in_attach":  false,
	"enable_query_cache":                   false,
	"enable_variadic_arraySetCheck":        true,
	"ntimes_slower_to_alarm":               uint64(3),
	"check_consistency":                    true,
	"max_parallel_threads_for_resharding":  uint64(32),
	"max_partitions_for_resharding":        uint64(4),

	"sort_overflow_mode": sort_overflow_mode,

	"result_overflow_mode": result_overflow_mode,

	"timeout_overflow_mode": timeout_overflow_mode,

	"set_overflow_mode": set_overflow_mode,

	"join_overflow_mode": join_overflow_mode,

	"transfer_overflow_mode": transfer_overflow_mode,

	"distinct_overflow_mode": distinct_overflow_mode,

	"max_network_bandwidth_for_fetch": uint64(0),
	"format_csv_delimiter":            ",",
	"format_csv_write_utf8_with_bom":  false,

	"format_protobuf_enable_multiple_message": true,
	"format_protobuf_default_length_parser":   false,
	"rm_zknodes_while_alter_engine":           false,
	"date_time_input_format":                  "FormatSettings",

	"mimic_replica_name":             "",
	"force_release_when_mmap_exceed": false,

	"asterisk_left_columns_only":    false,
	"kms_token":                     "",
	"encrypt_key":                   "",
	"enable_final_for_delta":        true,
	"slow_query_ms":                 uint64(0),
	"max_rows_to_schedule_merge":    uint64(500000000),
	"expired_start_hour_to_merge":   uint64(12),
	"expired_end_hour_to_merge":     uint64(12),
	"strict_rows_to_schedule_merge": uint64(50000000),
	"max_parts_to_optimize":         uint64(1000),
	"enable_merge_scheduler":        false,
	"max_rows_for_resharding":       uint64(10000000000),
	"conservative_merge_predicate":  true,
	"tealimit_order_keep":           false,
	"databases_load_pool_size":      uint64(3),
	"tables_load_pool_size":         uint64(8),
	"parts_load_pool_size":          uint64(48),
	"parts_preallocate_pool_size":   uint64(16),
	"connection_check_pool_size":    uint64(16),
	"query_auto_retry":              false,
	"query_auto_retry_millisecond":  uint64(QUERY_AUTO_RETRY_MILLISECOND),
	"process_list_block_time":       uint64(30000),

	"check_query_single_value_result": false,
	"enable_view_based_query_rewrite": false,

	"max_hdfs_write_buffer_size": uint64(DBMS_DEFAULT_BUFFER_SIZE),

	"input_format_max_map_key_long":        uint64(80),
	"input_format_parse_null_map_as_empty": true,
	"input_format_skip_null_map_value":     true,
	"cascading_refresh_materialized_view":  true,
	"batch_size_in_attaching_parts":        uint64(1024),
	"remote_query_memory_table":            false,
	"max_ingest_columns_size":              uint64(10),
	"max_ingest_rows_size":                 uint64(50000000),
	"aggressive_merge_in_optimize":         true,
	"enable_detail_event_log":              false,

	"max_compressed_bytes_to_read":   uint64(0),
	"max_uncompressed_bytes_to_read": uint64(0),

	"constraint_skip_violate":         false,
	"distributed_to_local":            false,
	"max_hdfs_read_network_bandwidth": uint64(0),
	"allow_map_access_without_key":    true,

	"debug_cnch_remain_temp_part":                      false,
	"debug_cnch_force_commit_parts_rpc":                false,
	"show_table_uuid_in_table_create_query_if_not_nil": true,

	"cnch_alter_task_timeout":                   uint64(200),
	"query_worker_fault_tolerance":              false,
	"virtual_warehouse_write":                   "",
	"restore_table_expression_in_distributed":   true,
	"catalog_enable_streaming_rpc":              true,
	"max_rpc_read_timeout_ms":                   uint64(10000),
	"preload_checksums_and_primary_index_cache": false,
	"enable_testlog_to_console":                 false,

	"enable_distributed_stages": false,

	"allow_experimental_map_type":   false,
	"allow_introspection_functions": false,

	"skip_history":          false,
	"ansi_sql":              false,
	"enable_query_metadata": false,
	"active_role":           "*",
	"log_id":                "",

	"virtual_warehouse": "",
}
