package protocol

const (
	VERSION_REVISION                                = 54428
	DBMS_MIN_REVISION_WITH_CLIENT_INFO              = 54032
	DBMS_MIN_REVISION_WITH_SERVER_TIMEZONE          = 54058
	DBMS_MIN_REVISION_WITH_QUOTA_KEY_IN_CLIENT_INFO = 54060
	DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME      = 54372
	DBMS_MIN_REVISION_WITH_VERSION_PATCH            = 54401
	DBMS_MIN_REVISION_WITH_SERVER_LOGS              = 54406
	DBMS_MIN_REVISION_WITH_COLUMN_DEFAULTS_METADATA = 54410

	DBMS_MIN_REVISION_WITH_DISK_CACHE_HIT_RATIO = 54419
)
