package param

const (
	COMPRESS                 string = "compress"
	USER                     string = "user"
	PASSWORD                 string = "password"
	DATABASE                 string = "database"
	TOKEN                    string = "token"
	ACCOUNT                  string = "account"
	TARGET_USER              string = "target_user"
	TARGET_ACCOUNT           string = "target_account"
	TARGET_ROLE              string = "target_role"
	TLS_CONFIG               string = "tls_config"
	NO_DELAY                 string = "no_delay"
	SECURE                   string = "secure"
	SKIP_VERIFICATION        string = "skip_verification"
	CONNECTION_TIMEOUT       string = "connection_timeout"
	RECEIVE_TIMEOUT          string = "receive_timeout"
	SEND_TIMEOUT             string = "send_timeout"
	BLOCK_SIZE               string = "block_size"
	POOL_SIZE                string = "pool_size"
	ALT_HOSTS                string = "alt_hosts"
	CONNECTION_OPEN_STRATEGY string = "connection_open_strategy"
	DEBUG                    string = "debug"
	QUOTA_KEY                string = "quota_key"
	SKIP_HISTORY             string = "skip_history"
	IS_SYSTEM                string = "is_system"
	REGION                   string = "region"
	ACCESS_KEY               string = "access_key"
	SECRET_KEY               string = "secret_key"
	VOLCANO                  string = "volcano"
)
